# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: catalog-service
#   name: catalog-service
#   namespace: cs3219
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: catalog-service
#     metadata:
#       labels:
#         app: catalog-service
#     spec:
#       containers:
#       - image: cs3219/catalog-service:1.0.0
#         imagePullPolicy: IfNotPresent
#         name: catalog-service
#         resources:
#           requests:
#             memory: "1Gi"
#             cpu: "500m"
#           limits:
#             memory: "1Gi"
#             cpu: "1000m"
#       restartPolicy: Always
# status: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: cs3219
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog
        image: eunrcn/catalog-service:1.0.0 
        ports:
        - containerPort: 8080
