# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: order-service
#   name: order-service
#   namespace: cs3219
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: order-service
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: order-service
#     spec:
#       containers:
#       - image: cs3219/order-service:1.0.0
#         imagePullPolicy: IfNotPresent
#         name: order-service
#         resources:
#           requests:
#             memory: "1Gi"
#             cpu: "500m"
#           limits:
#             memory: "1Gi"
#             cpu: "1000m"
#       restartPolicy: Always
# status: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cs3219
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order
        image: eunrcn/order-service:1.0.0
        ports:
        - containerPort: 8080
