# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: api-gateway
#   name: api-gateway
#   namespace: cs3219
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: api-gateway
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: api-gateway
#     spec:
#       containers:
#       - image: cs3219/api-gateway:1.0.0
#         imagePullPolicy: IfNotPresent
#         name: api-gateway
#         resources:
#           requests:
#             memory: "1Gi"
#             cpu: "500m"
#           limits:
#             memory: "1Gi"
#             cpu: "1000m"
#       restartPolicy: Always
# status: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cs3219
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: gateway
        image: eunrcn/api-gateway:1.0.0  
        ports:
        - containerPort: 8000 
